---
- name: Add user, group, and user to group
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - redhat_cop.ah_configuration
  tasks:
    - name: Remove collection
      ah_collection_manage:
        namespace: community_test
        name: test
        version: 1.0.1
        state: absent
        ah_host: https://ah.node
        ah_username: admin
        ah_password: secret123
        ah_path_prefix: galaxy
        validate_certs: false
      register: collection

    - debug:
        var: collection
