---
apiVersion: v1
kind: Pod
metadata:
  namespace: default
spec:
  serviceAccountName: default
  automountServiceAccountToken: false
  containers:
    - image: >-
        registry.redhat.io/ansible-automation-platform-22/ee-supported-rhel8:latest
      name: worker
      args:
        - ansible-runner
        - worker
        - '--private-data-dir=/runner'
      resources:
        requests:
          cpu: 250m
          memory: 100Mi
...
