---
- name: Add user, group, and user to group
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - redhat_cop.ah_configuration
  tasks:
    - name: Publish Collections
      redhat_cop.ah_configuration.ah_collection:
        namespace: sean_sullivan
        name: ah_configuration
        path: sean_sullivan-ah_configuration-4.1.2.tar.gz
        ah_host: https://ah.node
        ah_username: admin
        ah_password: secret123
        ah_path_prefix: galaxy
        validate_certs: false

