---
- name: Using module to update instance group.
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - ansible.controller
  tasks:
    - name: Create edge instance group with exec instance.
      ansible.controller.instance_group:
        name: edge
        instances:
          - controller
        controller_host: https://controller.node
        controller_username: admin
        controller_password: secret123
        validate_certs: false
...
