---
- name: Export Workflow
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - ansible.controller
  environment:
     CONTROLLER_HOST: https://controller.node/
     CONTROLLER_USERNAME: admin
     CONTROLLER_PASSWORD: secret123
     CONTROLLER_VERIFY_SSL: False

  tasks:
    - name: Export workflow job template
      ansible.controller.export:
        credential_types: 'all'
      register: export_results

    - debug:
        var: export_results

    - name: Export credential_types to file
      copy:
        content: "{{ export_results | to_nice_yaml( width=50, explicit_start=True, explicit_end=True) }}"
        dest: credential_types.yaml
...