---
- name: Launch Workflows via API
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    workflow_name: Complicated workflow schema
    workflow_extra_vars_dict:
      test: data
      variable: things
    workflow_node_to_check: Template 1
    approval_template_name: Aproval Node


  tasks:

    - name: "Launch Workflow {{ workflow_name }}"
      ansible.controller.workflow_launch:
        workflow_template:              "{{ workflow_name }}"
        extra_vars:                     "{{ workflow_extra_vars_dict | default(omit) }}"
        wait: false
        controller_host: https://controller.node
        controller_username: admin
        controller_password: secret123
        validate_certs: false
      register: workflow_data

    - debug:
        var: workflow_data

    - name: Wait for a workflow node to finish
      ansible.controller.workflow_node_wait:
        workflow_job_id: "{{ workflow_data.id }}"
        name: "{{ workflow_node_to_check }}"
        timeout: 90
        controller_host: https://controller.node
        controller_username: admin
        controller_password: secret123
        validate_certs: false
      register: node_lookup_results
      ignore_errors: true

    - name: Wait for approval node to activate and approve
      ansible.controller.workflow_approval:
        workflow_job_id: "{{ workflow_data.id }}"
        name: "{{ approval_template_name }}"
        interval: 5
        timeout: 20
        action: approve
        controller_host: https://controller.node
        controller_username: admin
        controller_password: secret123
        validate_certs: false

    - name: Wait for Workflow to finish
      ansible.controller.job_wait:
        job_id:                         "{{ workflow_data.id }}"
        job_type:                       "workflow_jobs"
        interval:                       5
        timeout:                        60
        controller_host: https://controller.node
        controller_username: admin
        controller_password: secret123
        validate_certs: false
...
