---
- name: Create Organization
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - ansible.controller
  tasks:
    - name: Get list of organizations
      uri:
        url: https://aap.lab.local/api/v2/organizations/
        user: admin
        password: Proteu690201
        method: GET
        validate_certs: false
        force_basic_auth: true
        status_code: 200
      register: organizations

    - name: List Organizations
      debug:
        var: organizations.json.results
...
