---
- name: Playbook add user and team and user to team
  hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
    - name: Include vars from configs directory
      include_vars:
        dir: ./configs
  roles:
    - redhat_cop.ah_configuration.group
    - redhat_cop.ah_configuration.user
...
