---
controller_settings:
  settings:
    AUTH_LDAP_SERVER_URI: 'LDAP://server2022.ansible.lcl'
    AUTH_LDAP_BIND_DN: 'CN=Administrator,CN=Users,DC=ansible,DC=lcl'
    AUTH_LDAP_BIND_PASSWORD: $encrypted$
    AUTH_LDAP_USER_SEARCH:
      - 'CN=Users,DC=ansible,DC=lcl'
      - SCOPE_SUBTREE
      - (sAMAccountName=%(user)s)
    AUTH_LDAP_USER_DN_TEMPLATE: null
    AUTH_LDAP_USER_ATTR_MAP:
      first_name: givenName
      last_name: sn
      email: mail
    AUTH_LDAP_GROUP_SEARCH:
      - 'CN=Users,DC=ansible,DC=lcl'
      - SCOPE_SUBTREE
      - (objectClass=group)
    AUTH_LDAP_GROUP_TYPE: MemberDNGroupType
    AUTH_LDAP_GROUP_TYPE_PARAMS:
      member_attr: member
      name_attr: cn
    AUTH_LDAP_REQUIRE_GROUP: null
    AUTH_LDAP_DENY_GROUP: null
    AUTH_LDAP_USER_FLAGS_BY_GROUP:
      is_superuser:
        - 'CN=ansible_admin,CN=Users,DC=ansible,DC=lcl'
    AUTH_LDAP_ORGANIZATION_MAP:
      Default:
        users:
          - 'CN=ansible,CN=Users,DC=ansible,DC=lcl'
          - 'CN=ansible_admin,CN=Users,DC=ansible,DC=lcl'
        admins: 'CN=ansible_admin,CN=Users,DC=ansible,DC=lcl'
        remove_admins: true
    AUTH_LDAP_TEAM_MAP:
      LDAP Engineering:
        organization: LDAP Organization
        remove: true
        users: 'cn=engineering,ou=groups,DC=ansible,DC=lcl'
      LDAP IT:
        organization: LDAP Organization
        remove: true
        users: 'cn=it,ou=groups,DC=ansible,DC=lcl'
      LDAP Sales:
        organization: LDAP Organization
        remove: true
        users: 'cn=sales,ou=groups,DC=ansible,DC=lcl'
...
