---
- name: Using role to set splunk settings
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    controller_hostname: https://controller.node
    controller_username: admin
    controller_password: secret123
    controller_validate_certs: false
    controller_settings:
      settings:
        LOG_AGGREGATOR_HOST: https://10.242.42.215/services/collector/event
        LOG_AGGREGATOR_PORT: 8088
        LOG_AGGREGATOR_TYPE: splunk
        LOG_AGGREGATOR_USERNAME: admin
        LOG_AGGREGATOR_PASSWORD: ae231e54-eee7-423b-9962-ed9ffdac4a99
        LOG_AGGREGATOR_INDIVIDUAL_FACTS: true
        LOG_AGGREGATOR_ENABLED: true
        LOG_AGGREGATOR_VERIFY_CERT: false
  collections:
    - ansible.controller
    - redhat_cop.controller_configuration
  roles:
    - redhat_cop.controller_configuration.settings
...
