---
controller_inventories:
  - name: Basic Inventory
    description: Create Inventory once piece at a time
    organization: Default
    variables:
      inventory_var: inventory_value
controller_hosts:
  - name: basic_host
    inventory: Basic Inventory
    variables:
      hosts_var: some_val
controller_groups:
  - name: Basic Group2
    inventory: Basic Inventory
  - name: Basic Group
    inventory: Basic Inventory
    variables:
      groups_variable: group_val
    hosts:
      - basic_host
    children:
      - Basic Group2
    preserve_existing_hosts: True
    preserve_existing_children: True
...
