---
- name: Playbook to create custom EE
  hosts: localhost  # controller.node
  gather_facts: false
  collections:
    - redhat_cop.ee_utilities
  vars:
    ee_registry_dest: hub
    ee_builder_dir_clean: true
    ee_ah_host: hub
    ee_ah_token: 39c1cbdd87fa4d00b3cfcea504a2c035115f2448
    ee_registry_username: admin
    ee_registry_password: secret123
    ee_validate_certs: false
    base_registery_username: username
    base_registery_password: password
    ee_list:
      - name: custom_ee
        # base_image
        bindep:
          - python38-requests [platform:centos-8 platform:rhel-8]
          - python38-pyyaml [platform:centos-8 platform:rhel-8]
        python:
          - pytz  # for schedule_rrule lookup plugin
          - python-dateutil>=2.7.0  # schedule_rrule
          - awxkit  # For import and export modules
        collections:
          - name: awx.awx
            version: 12.0.0
          - name: redhat_cop.controller_configuration
          - name: redhat_cop.ah_configuration
        prepend:
          - RUN whoami
          - RUN cat /etc/os-release
        append:
          - RUN echo This is a post-install command!
  roles:
    - redhat_cop.ee_utilities.ee_builder
...
