---
- name: Playbook to create custom EE
  hosts: tower
  gather_facts: false
  collections:
    - redhat_cop.ee_utilities
  vars:
    venv_migrate_default_ee_url: ah.node/ee-minimal-rhel8:latest
  tasks:
    - name: Include venv_migrate role
      include_role: 
        name: redhat_cop.ee_utilities.virtualenv_migrate

    - set_fact:
        venv_migrate_ee_python: "{{ {} | combine(venv_migrate_ee_python_list) }}"
 


- name: Build EEs with ee_builder role
  hosts: localhost
  vars:
    venv_migrate_default_ee_url: ah.node/ee-minimal-rhel8:latest
    ee_registry_dest: ah.node/
    ee_bindep: []
    ee_collections:
      - name: awx.awx
      - name: redhat_cop.controller_configuration
      - name: redhat_cop.ah_configuration
  tasks:
    - set_fact:
         venv_migrate_ee_python: "{{ hostvars[groups['tower'][0]]['venv_migrate_ee_python'] }}"

    - name: Create EEs
      include_tasks: create_ee.yml
      loop: "{{ venv_migrate_ee_python | dict2items }}"

    - name: Export python virtual enviroment list to file
      copy:
        content: "{{ venv_migrate_ee_python | to_nice_yaml( width=50, explicit_start=True, explicit_end=True) }}"
        dest: venv_migrate_ee_python.yaml