---
- name: Playbook to add change controller settings
  hosts: localhost
  connection: local
  collections:
    - ansible.controller
    - redhat_cop.controller_configuration
  pre_tasks:
    - name: Include vars from configs directory
      include_vars:
        dir: ./config
  roles:
    - redhat_cop.controller_configuration.inventories
    - redhat_cop.controller_configuration.hosts
    - redhat_cop.controller_configuration.groups
...
