---
- name: Updating Automation Repositories
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - redhat_cop.ah_configuration
  vars:
    ah_host: https://ah.node/
    ah_username: admin
    ah_password: secret123
    ah_path_prefix: galaxy
    ah_validate_certs: false
  pre_tasks:
    - name: Include vars from configs directory
      include_vars:
        dir: ./configs
  tasks:
    - name: Create namespace
      include_role:
        name: redhat_cop.ah_configuration.namespace

    - name: Publish Collections
      include_role:
        name: redhat_cop.ah_configuration.publish
      vars:
        ah_auto_approve: true
        ah_overwrite_existing: true

    - name: Upload collection to automation hub
      redhat_cop.ah_configuration.ah_collection:
        namespace: awx
        name: awx
        path: /var/tmp/collections/community_test-awx-0.0.15.tar.gz

...
