---
- name: Updating Automation Repositories
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - redhat_cop.ah_configuration

  tasks:

    - name: Configure community repo
      redhat_cop.ah_configuration.ah_repository:
        name: community
        url: https://galaxy.ansible.com/api/
        requirements:
          - name: redhat_cop.ah_configuration
          - name: redhat_cop.tower_configuration
        ah_host: https://ah.node/
        ah_username: admin
        ah_password: secret123
        ah_path_prefix: galaxy
        validate_certs: false

    - name: Configure community repo from file
      redhat_cop.ah_configuration.ah_repository:
        name: community
        url: https://galaxy.ansible.com/api/
        requirements_file: requirements.yml
        ah_host: https://ah.node/
        ah_username: admin
        ah_password: secret123
        ah_path_prefix: galaxy
        validate_certs: false

    - name: Sync community repo
      redhat_cop.ah_configuration.ah_repository_sync:
        name: community
        wait: true
        ah_host: https://ah.node/
        ah_username: admin
        ah_password: secret123
        ah_path_prefix: galaxy
        validate_certs: false

    - name: Configure rh-certified repo
      redhat_cop.ah_configuration.ah_repository:
        name: rh-certified
        url: https://console.redhat.com/api/automation-hub/
        auth_url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
        token: aabbcc
        ah_host: https://ah.node/
        ah_username: admin
        ah_password: secret123
        ah_path_prefix: galaxy
        validate_certs: false

    - name: Sync rh-certified repo
      redhat_cop.ah_configuration.ah_repository_sync:
        name: rh-certified
        wait: true
        ah_host: https://ah.node/
        ah_username: admin
        ah_password: secret123
        ah_path_prefix: galaxy
        validate_certs: false
...
