---
- name: Playbook to Create controller Credentials with api
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Find the data to get organization id
      uri:
        url: https://controller.node/api/v2/organizations/?name=Default
        user: admin
        password: secret123
        method: GET
        validate_certs: false
        force_basic_auth: true
        status_code: 200
        body_format: json
      register: organization_data

    - name: List Result
      debug:
        var: organization_data.json.results[0].id

    - name: Find the data to get credential type id
      uri:
        url: https://controller.node/api/v2/credential_types/?name=REST+API+Credential
        user: admin
        password: secret123
        method: GET
        validate_certs: false
        force_basic_auth: true
        status_code: 200
        body_format: json
      register: credential_type

    - name: List Result
      debug:
        var: credential_type.json.results[0].id

    - name: Create Credentials
      uri:
        url: https://controller.node/api/v2/credentials/
        user: admin
        password: secret123
        method: POST
        validate_certs: false
        force_basic_auth: true
        status_code: 201
        body_format: json
        body:
          name: REST API Credential
          description: REST API Credential
          organization: "{{ organization_data.json.results[0].id }}"
          credential_type: "{{ credential_type.json.results[0].id }}"
          inputs:
            rest_username: rest_user
            rest_password: password
      register: credential_api

    - name: List Result
      debug:
        var: credential_api
...
