---
- name: Export credential Types
  hosts: localhost
  gather_facts: false
  collections:
    - awx.awx
    - redhat_cop.controller_configuration
  connection: local
  vars:
    controller_hostname: https://controller.node
    controller_username: admin
    controller_password: secret123
    controller_validate_certs: false

  tasks:
    - name: "Get the API of all credential types"
      set_fact:
        credential_types_api_results: "{{ lookup('awx.awx.controller_api', 'credential_types' ,host=controller_hostname, username=controller_username, password=controller_password, verify_ssl=false, return_all=True) |sort(attribute='id') }}"

    - debug:
        var: credential_types_api_results

    - name: Export credential types to a file
      copy:
        content: "{{ credential_types_api_results | to_nice_yaml( width=50, explicit_start=True, explicit_end=True) }}"
        dest: credential_types.yaml

    - name: Export credential type names to file
      copy:
        content: "{{ credential_types_api_results | map(attribute='name') | to_nice_yaml( width=50, explicit_start=True, explicit_end=True) }}"
        dest: credential_types_names.yaml
...
