---
- name: Add notification template.
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - ansible.controller
  tasks:
    - name: Add Slack notification with custom messages
      ansible.controller.notification_template:
        name: Slack_notification
        description: ''
        organization: Default
        notification_type: slack
        notification_configuration:
          channels:
            - notification_test  # group_approval_notification
          token: xoxb-964864867521-1933681026007-lXrfEmQUU5TZ2y1icFxCkX6H
        messages:
          started:
            message: "{{ '{{ job_friendly_name }}{{ job.id }} started' }}"
          success:
            message: "{{ '{{ job_friendly_name }} completed in {{ job.elapsed }} seconds' }}"
          error:
            message: "{{ '{{ job_friendly_name }} FAILED! Please look at {{ job.url }}' }}"
        controller_host: https://10.0.0.1
        controller_username: admin
        controller_password: password
        validate_certs: false

    - name: Create the Hello world tower project
      ansible.controller.project:
        name: Tower Test Project
        scm_type: git
        scm_url: https://github.com/ansible/tower-example.git
        scm_branch: master
        scm_clean: true
        description: Tower Hello World
        organization: Default
        wait: true
        update: true
        notification_templates_error:
          - Slack_notification
        controller_host: https://10.0.0.1
        controller_username: admin
        controller_password: password
        validate_certs: false
...
