---
- name: Playbook add notifications
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    controller_hostname: https://10.0.0.1
    controller_username: admin
    controller_password: password
    controller_validate_certs: false
    controller_notifications:
      - name: Gmail notification
        description: Notify us on Google
        organization: Default
        notification_type: email
        notification_configuration:
          username: asdf@gmail.com
          password: tnbfksktebythfwv
          host: smtp.gmail.com
          recipients:
            - asdf@gmail.com
          sender: asdf@gmail.com
          port: 587
          timeout: 60
          use_tls: true
          use_ssl: false
        messages:
          success:
            body: '{"fields": {"project": {"id": "11111"},"summary": "Lab {  { job.status
              }} Ansible Controller {  { job.name }}","description": "{  { job.status }} in {  {
              job.name }} {  { job.id }} {  {url}}","issuetype": {"id": "1"}}}'
      - name: Slack_approval_notification
        description: ''
        organization: Default
        notification_type: slack
        notification_configuration:
          channels:
            - notification_test  # group_approval_notification
          token: xoxb-964864867521-1933681026007-lXrfEmQUU5TZ2y1icFxCkX6H
          use_ssl: false
          use_tls: false
        messages:
          workflow_approval:
            approved:
              body:
              message: "{  {job.name }}"
              # Job.name does not populate and thus does not send message, Change to start sending messages for this event.
            denied:
              body:
              message: "{  {job.name }}"
              # Job.name does not populate and thus does not send message, Change to start sending messages for this event.
            running:
              body:
              message: 'The approval node "{  { approval_node_name }}" needs review. This node can be viewed at: {  { workflow_url }}, job data: {  { job_metadata }}'
            timed_out:
              body:
              message: "{  {job.name }}"
              # Job.name does not populate and thus does not send message, Change to start sending messages for this event.

    controller_projects:
      - name: Test Project
        scm_type: git
        scm_url: https://github.com/ansible/tower-example.git
        scm_branch: master
        scm_clean: true
        description: Test Project 1
        organization: Default
        wait: true
        update: true
        notification_templates_error:
          - Gmail notification
        notification_templates_started: []
        notification_templates_success: []
        notification_templates_approvals: []

  collections:
    - awx.awx
    - redhat_cop.controller_configuration
  roles:
    - redhat_cop.controller_configuration.notification_templates
    - redhat_cop.controller_configuration.projects
...
