---
- name: Add notification template.
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - ansible.controller
  tasks:
    - name: Add Slack notification with custom messages
      ansible.controller.notification_template:
        name: Slack_notification
        description: ''
        organization: Default
        notification_type: slack
        notification_configuration:
          channels:
            - notification_test  # group_approval_notification
          token: xoxb-aabbcc
        messages:
          started:
            message: "{{ '{{ job_friendly_name }}{{ job.id }} started' }}"
          success:
            message: "{{ '{{ job_friendly_name }} completed in {{ job.elapsed }} seconds, job data: {{ job_metadata }}' }}"
          error:
            message: "{{ '{{ job_friendly_name }} FAILED! Please look at {{ job.url }}' }}"
        controller_host: https://controller.node
        controller_username: admin
        controller_password: Proteu690201
        validate_certs: false

    - name: Create the Test project
      ansible.controller.project:
        name: Test Project
        scm_type: git
        scm_url: https://github.com/ansible/test-playbooks.git
        scm_branch: master
        scm_clean: true
        description: Test Project
        organization: Default
        wait: true
        update_project: true
        notification_templates_error:
          - Slack_notification
        notification_templates_success:
          - Slack_notification
        controller_host: https://controller.node
        controller_username: admin
        controller_password: Proteu690201
        validate_certs: false
...
