---
- name: Playbook add role to a team
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    controller_hostname: https://controller.node
    controller_username: admin
    controller_password: secret123
    controller_validate_certs: false
    controller_user_accounts:
      - user: joe123
        is_superuser: false
        password: password123
    controller_teams:
      - name: satlab
        organization: Default
    controller_roles:
      - projects:
          - Demo Project
        job_templates:
          - Demo Job Template
        team: satlab
        role: admin
      - projects:
          - Demo Project
        job_templates:
          - Demo Job Template
        user: joe123
        role: admin
  collections:
    - awx.awx
    - redhat_cop.controller_configuration
  roles:
    - redhat_cop.controller_configuration.users
    - redhat_cop.controller_configuration.teams
    - redhat_cop.controller_configuration.roles
...
