---
- name: Add admin of inventory to user
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - ansible.controller
  tasks:
    - name: Set user to admin over inventory
      ansible.controller.role:
        user: joe123
        role: admin
        inventories: 
          - Demo Inventory
        controller_host: https://10.0.0.1
        controller_username: admin
        controller_password: password
        validate_certs: false
...
