controller_credentials:
  - credential_type: REST API Credential
    name: REST API Credential
    description: REST API Credential
    organization: Default
    inputs:
      rest_username: rest_user
      rest_password: password
  - credential_type: Red Hat Virtualization
    name: RHVM
    organization: Default
    description: infra-rhvm-01 creds for inventory sources.
    inputs:
      host: "https://example.com/ovirt-engine/api"
      username: user
      password: password