---
controller_projects:
  - name: Inventory example
    scm_type: git
    scm_url: https://github.com/sean-m-sullivan/inventory_example.git
    scm_branch: main
    description: Inventory Example
    organization: Default
    wait: true
    update: true
  - name: Test Project
    scm_type: git
    scm_url: https://github.com/ansible/test-playbooks.git
    scm_branch: master
    scm_clean: true
    description: Test Project 1
    organization: Default
    wait: true
    update: true

...
