---
- name: Playbook to add change controller settings
  hosts: localhost
  connection: local
  collections:
    - awx.awx
    - redhat_cop.controller_configuration
  pre_tasks:
    - name: Include vars from configs directory
      include_vars:
        dir: ./configs
  roles:
    - redhat_cop.controller_configuration.license
    - redhat_cop.controller_configuration.settings
...
