---
- name: Using module to create project
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - ansible.controller
  tasks:
    - name: Create the test project
      ansible.controller.project:
        name: Test Project
        scm_type: git
        scm_url: https://github.com/ansible/test-playbooks.git
        scm_branch: master
        scm_clean: true
        description: Test project
        organization: Default
        wait: true
        update_project: true
        controller_host: https://controller.node
        controller_username: admin
        controller_password: secret123
        validate_certs: false
...
