---
controller_inventories:
  - name: Basic Inventory
    description: Create Inventory once piece at a time
    organization: Default
    variables:
      inventory_var: inventory_value
controller_projects:
  - name: Inventory example
    scm_type: git
    scm_url: https://github.com/sean-m-sullivan/inventory_example.git
    scm_branch: main
    scm_clean: true
    description: Inventory Example
    organization: Default
    wait: true
    update: true
controller_inventory_sources:
  - name: Public APIs
    source: scm
    source_project: Inventory example
    source_path: inventories/plugin.yml
    inventory: Basic Inventory
    organization: Default
    overwrite: true
    update_on_launch: true
    update_cache_timeout: 0
    wait: true
...
