---
- name: "Set per host stats"
  hosts: "{{ host_groups }}"
  gather_facts: false

  tasks:

    - debug:
        var: var_per_host

# Results:
# var_per_host:
#   hostname1:
#     other_info: 1
#   hostname2:
#     other_info: 1
#   hostname3:
#     other_info: 1

# use in a later play: "{{ var_per_host[inventory_hostname] }}"
...
