---
- name: Publish collection
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Publish Collection
      redhat_cop.ah_configuration.ah_collection:
        namespace: custom_collection_space
        name: custom_collection
        path: custom_collection_space-custom_collection-1.0.0.tar.gz
        auto_approve: false
        ah_host: https://hub.node
        ah_username: admin
        ah_password: secret123
        ah_path_prefix: galaxy
        validate_certs: false
...
