---
- name: Create Inventory source
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - ansible.controller
  tasks:
    - name: Add project
      ansible.controller.project:
        name: Inventory example
        scm_type: git
        scm_url: https://github.com/sean-m-sullivan/inventory_example.git
        scm_branch: main
        description: Inventory Example
        organization: Default
        state: present
        controller_host: https://controller.node
        controller_username: admin
        controller_password: Proteu690201
        validate_certs: false

    - name: Add inventory
      ansible.controller.inventory:
        name: Basic Inventory
        description: Create Inventory once piece at a time
        organization: Default
        state: present
        controller_host: https://controller.node
        controller_username: admin
        controller_password: Proteu690201
        validate_certs: false

    - name: Add inventory source
      ansible.controller.inventory_source:
        name: Public APIs
        source: scm
        source_project: Inventory example
        source_path: inventories/plugin.yml
        inventory: Basic Inventory
        organization: Default
        overwrite: true
        update_on_launch: true
        update_cache_timeout: 0
        state: present
        controller_host: https://controller.node
        controller_username: admin
        controller_password: Proteu690201
        validate_certs: false

    - name: Update a single inventory source
      ansible.controller.inventory_source_update:
        name: Public APIs
        inventory: Basic Inventory
        organization: Default
        controller_host: https://controller.node
        controller_username: admin
        controller_password: Proteu690201
        validate_certs: false
...
