---
- name: Launch update on project
  hosts: localhost
  connection: local
  gather_facts: false

  # Import controller vars and test case vars
  environment:
    CONTROLLER_VERIFY_SSL: false
  tasks:
    - name: Update Project
      ansible.controller.project_update:
        name: Test Project
        organization: Default
        wait: true
        timeout: 600
        interval: 10
        controller_host: https://controller.node
        controller_username: admin
        controller_password: secret123
        validate_certs: false
...
