# User may add auth creds to this file and encrypt it using `ansible-vault`
---
ah_host: https://ah.node
ah_username: admin
ah_password: Proteu690201
ah_path_prefix: galaxy
ah_validate_certs: false
...
