---
- name: Using role create job template
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    controller_hostname: https://controller.node
    controller_username: admin
    controller_password: secret123
    controller_validate_certs: false
    controller_configuration_credentials_secure_logging: false
    controller_configuration_async_delay: 4
    controller_configuration_workflow_async_retries: 50
    controller_projects:
      - name: Test Project
        scm_type: git
        scm_url: https://github.com/ansible/test-playbooks.git
        scm_branch: master
        scm_clean: true
        description: Test Project 1
        organization: Default
        wait: true
        update: true
    controller_inventories:
      - name: RHVM-01
        organization: Default
        description: created by Ansible Playbook - for RHVM-01
    controller_inventory_sources:
      - name: RHVM-01
        source: scm
        source_project: Test Project
        source_path: phillips_hue/hosts
        inventory: RHVM-01
        organization: Default
        overwrite: true
        update_on_launch: true
        update_cache_timeout: 0
        wait: false
    controller_credentials:
      - credential_type: Red Hat Virtualization
        name: RHVM
        organization: Default
        description: infra-rhvm-01 creds for inventory sources.
        inputs:
          host: "https://example.com/ovirt-engine/api"
          username: user
          password: password
    controller_templates:
      - name: test-template-1
        description: created by Ansible Playbook
        job_type: run
        inventory: 8
        credentials:
          - RHVM
        project: Test Project
        playbook: chatty_payload.yml
        verbosity: 2
        extra_vars:
          target_hosts: infra-ansible-01.example.com
        survey_spec:
          name: Survey Example template
          description: Description goes here
          spec:
            - question_name: Target Host
              question_description: target host is required for playbook to work, this host
                needs to exist in the inventory
              required: true
              type: text
              variable: target_hosts
              min: 0
              max: 1024
              default: infra-ansible-testing.infra.sat.rdu2.redhat.com
              choices: ''
              new_question: true
    controller_workflows:
      - name: Complicated workflow schema
        destroy_current_schema: true
        survey_enabled: true
        survey_spec:
          name: Survey Example template
          description: Description goes here
          spec:
            - question_name: text
              question_description: >-
                target host is required for playbook to work, this host needs to exist in
                the inventory
              required: true
              type: text
              variable: text
              min: 0
              max: 1034
              default: infra-ansible-testing.infra.sat.rdu2.redhat.com
              choices: ''
              formattedChoices:
                - choice: ''
                  isDefault: false
                  id: 0
            - question_name: textarea
              question_description: ''
              required: true
              type: textarea
              variable: textarea
              min: 0
              max: 1024
              default: ''
              choices: ''
            - question_name: password
              question_description: ''
              required: true
              type: password
              variable: password
              min: 0
              max: 1024
              default: ''
              choices: ''
            - question_name: multiple_single
              question_description: ''
              required: true
              type: multiplechoice
              variable: multiple_single
              min: 0
              max: 1024
              formattedChoices:
                - choice: asdf
                  isDefault: true
                  id: 0
                - choice: fsad
                  isDefault: false
                  id: 1
                - choice: sad
                  isDefault: false
                  id: 2
                - choice: dad
                  isDefault: false
                  id: 3
              default: asdf
              choices: |-
                asdf
                fsad
                sad
                dad
            - question_name: multiple_select
              question_description: ''
              required: true
              type: multiselect
              variable: multiple_select
              min: 0
              max: 1024
              default: |-
                asdf
                fdas
              choices: |-
                asdf
                fdas
                sad
                dad
            - question_name: integer
              question_description: ''
              required: true
              type: integer
              variable: integer
              min: 0
              max: 3
              default: 2
              choices: ''
            - question_name: float
              question_description: ''
              required: true
              type: float
              variable: float
              min: 0
              max: 1024
              default: 2.5
              choices: ''
        related:
          workflow_nodes:
            - identifier: Inventory Update
              related:
                success_nodes:
                  - identifier: Template 1
              unified_job_template:
                inventory:
                  organization:
                    name: Default
                name: RHVM-01
                type: inventory_source
            - identifier: Project Update
              related:
                success_nodes:
                  - identifier: Template 1
              unified_job_template:
                name: Test Project
                organization:
                  name: Default
                type: project
            - identifier: Template 1
              all_parents_must_converge: true
              related:
                success_nodes:
                  - identifier: Template 2
                failure_nodes:
                  - identifier: Approval Node
              unified_job_template:
                name: test-template-1
                organization:
                  name: Default
                type: job_template
            - identifier: Approval Node
              related:
                success_nodes:
                  - identifier: Template 2
              unified_job_template:
                description: Approval node for example
                timeout: 900
                type: workflow_approval
                name: Approval to continue
            - identifier: Template 2
              unified_job_template:
                name: test-template-1
                organization:
                  name: Default
                type: job_template

  collections:
    - ansible.controller
    - redhat_cop.controller_configuration
  roles:
    - redhat_cop.controller_configuration.credentials
    - redhat_cop.controller_configuration.inventories
    - redhat_cop.controller_configuration.inventory_sources
    - redhat_cop.controller_configuration.projects
    - redhat_cop.controller_configuration.job_templates
    - redhat_cop.controller_configuration.workflow_job_templates
...
