---
- name: Launch Workflows via API
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Launch an ad hoc command
      ansible.controller.ad_hoc_command:
        module_name: shell
        module_args: ls -a
        inventory: Demo Inventory
        credential: Demo Credential
        wait: false
        controller_host: https://controller.node
        controller_username: admin
        controller_password: secret123
        validate_certs: false
      register: command

    - name: Wait for ad job command max 120s
      ansible.controller.ad_hoc_command_wait:
        command_id: "{{ command.id }}"
        timeout: 120
        controller_host: https://controller.node
        controller_username: admin
        controller_password: secret123
        validate_certs: false

    - name: Wait for ad job command max 120s
      ansible.controller.ad_hoc_command_cancel:
        command_id: "{{ command.id }}"
        timeout: 120
        controller_host: https://controller.node
        controller_username: admin
        controller_password: secret123
        validate_certs: false
...
